// Fetches Archivo + IBM Plex Mono from Google Fonts and self-hosts them under
// public/fonts, emitting src/styles/fonts.css. The handoff requires self-hosting;
// this script exists so that step is reproducible rather than a one-off download.
//
//   node scripts/fetch-fonts.mjs
//
// Latin subset only — the UI ships no non-latin copy. Google serves Archivo as a
// single variable file for every weight we ask for, so identical URLs are collapsed
// into one @font-face with a weight range.

import { mkdirSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';

const API = 'https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&display=block';
// css2 serves woff2-only CSS to browser UAs and legacy formats to everything else.
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';

const css = execFileSync('curl', ['-sSf', '-A', UA, API], { encoding: 'utf8' });

/** @type {Map<string, {family: string, slug: string, weights: number[], range: string}>} */
const byUrl = new Map();

for (const block of css.split('@font-face').slice(1)) {
  const family = /font-family: '([^']+)'/.exec(block)?.[1];
  const weight = /font-weight: (\d+)/.exec(block)?.[1];
  const url = /url\((https:[^)]+)\)/.exec(block)?.[1];
  const range = /unicode-range: ([^;]+);/.exec(block)?.[1];
  if (!family || !weight || !url || !range?.includes('U+0000-00FF')) continue;

  const entry = byUrl.get(url);
  if (entry) {
    entry.weights.push(Number(weight));
  } else {
    const slug = family.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    byUrl.set(url, { family, slug, weights: [Number(weight)], range: range.trim() });
  }
}

if (byUrl.size === 0) throw new Error('no latin faces found — did the css2 response format change?');

mkdirSync('public/fonts', { recursive: true });

const faces = [];
for (const [url, { family, slug, weights, range }] of byUrl) {
  const min = Math.min(...weights);
  const max = Math.max(...weights);
  // One family can resolve to several distinct files (static instances) or to a single
  // variable file serving every weight — name by the weight range so neither collides.
  const file = `${slug}-${min === max ? min : `${min}-${max}`}.woff2`;
  execFileSync('curl', ['-sSf', '-o', `public/fonts/${file}`, url]);
  faces.push(`@font-face {
  font-family: '${family}';
  font-style: normal;
  font-weight: ${min === max ? min : `${min} ${max}`};
  font-display: block;
  src: url('/fonts/${file}') format('woff2');
  unicode-range: ${range};
}`);
}

writeFileSync(
  'src/styles/fonts.css',
  `/* GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.\n   Latin subset only. Rerun the script to refresh. */\n\n${faces.join('\n\n')}\n`,
);

console.log(`wrote ${faces.length} face(s) to src/styles/fonts.css`);
